{{- if .Values.clusterRole.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.appName }}

rules:
  - apiGroups:
      - ''
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
{{- end }}